// Code generated by gen/gen.c; DO NOT EDIT.

package std

type (
	c_char                int8
	c_signed_char         int8
	c_unsigned_char       uint8
	c_short               int16
	c_unsigned_short      uint16
	c_int                 int32
	c_unsigned_int        uint32
	c_long                int64
	c_unsigned_long       uint64
	c_longlong            int64
	c_unsigned_longlong   uint64
	c_float               float32
	c_double              float64
	c_int8_t              int8
	c_int16_t             int16
	c_int32_t             int32
	c_int64_t             int64
	c_uint8_t             uint8
	c_uint16_t            uint16
	c_uint32_t            uint32
	c_uint64_t            uint64
	c_uintptr_t           uint64
	c_size_t               uint64
	c_time_t               int64
	c_clock_t              int64
	c_bool                 uint8
)
